# Generated by Django 5.2.3 on 2025-07-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_glutenfreehotel_website_alter_glutenfreehotel_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='glutenfreehotel',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='İlçe'),
        ),
    ]
