# Generated by Django 5.2.3 on 2025-07-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_glutenfreehotel_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glutenfreehotel',
            name='city',
            field=models.CharField(max_length=30, verbose_name='Şehir'),
        ),
    ]
