# Generated by Django 5.2.3 on 2025-07-12 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_glutenfreehotel_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glutenfreehotel',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_%(class)s_items', to=settings.AUTH_USER_MODEL, verbose_name='Added By'),
        ),
        migrations.AlterField(
            model_name='glutenfreehotel',
            name='city',
            field=models.CharField(max_length=30, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='glutenfreehotel',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='glutenfreehotel',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
    ]
