# Generated by Django 5.2.3 on 2025-07-12 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_glutenfreehotel_added_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='glutenfreevenue',
            name='city',
            field=models.CharField(default='Ankara', max_length=30, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='glutenfreevenue',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Brand Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='glutenfreefood',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_%(class)s_items', to=settings.AUTH_USER_MODEL, verbose_name='Added By'),
        ),
        migrations.AlterField(
            model_name='glutenfreefood',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.brand', verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='glutenfreefood',
            name='category',
            field=models.ManyToManyField(blank=True, to='users.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='glutenfreemedicine',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_%(class)s_items', to=settings.AUTH_USER_MODEL, verbose_name='Added By'),
        ),
        migrations.AlterField(
            model_name='glutenfreemedicine',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.brand', verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='glutenfreerecipe',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_%(class)s_items', to=settings.AUTH_USER_MODEL, verbose_name='Added By'),
        ),
        migrations.AlterField(
            model_name='glutenfreevenue',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_%(class)s_items', to=settings.AUTH_USER_MODEL, verbose_name='Added By'),
        ),
    ]
