# Generated by Django 5.2.3 on 2025-07-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_glutenfreevenue_city_glutenfreevenue_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='glutenfreevenue',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Web Sitesi'),
        ),
    ]
