# Generated by Django 4.2.7 on 2025-07-15 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_glutenfreehotel_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Marka', 'verbose_name_plural': 'Markalar'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategori', 'verbose_name_plural': 'Kategoriler'},
        ),
        migrations.AlterModelOptions(
            name='foodbrand',
            options={'verbose_name': 'Gıda Markası', 'verbose_name_plural': 'Gıda Markaları'},
        ),
        migrations.AlterModelOptions(
            name='glutenfreefood',
            options={'verbose_name': 'Glutensiz Gıda', 'verbose_name_plural': 'Glutensiz Gıdalar'},
        ),
        migrations.AlterModelOptions(
            name='glutenfreehotel',
            options={'verbose_name': 'Glutensiz Otel', 'verbose_name_plural': 'Glutensiz Oteller'},
        ),
        migrations.AlterModelOptions(
            name='glutenfreemedicine',
            options={'verbose_name': 'Glutensiz İlaç', 'verbose_name_plural': 'Glutensiz İlaçlar'},
        ),
        migrations.AlterModelOptions(
            name='glutenfreerecipe',
            options={'verbose_name': 'Glutensiz Tarif', 'verbose_name_plural': 'Glutensiz Tarifler'},
        ),
        migrations.AlterModelOptions(
            name='glutenfreevenue',
            options={'verbose_name': 'Glutensiz Mekan', 'verbose_name_plural': 'Glutensiz Mekanlar'},
        ),
        migrations.AlterModelOptions(
            name='medicinebrand',
            options={'verbose_name': 'İlaç Markası', 'verbose_name_plural': 'İlaç Markaları'},
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Marka Adı'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Kategori Adı'),
        ),
        migrations.AlterField(
            model_name='foodbrand',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Gıda Markası'),
        ),
        migrations.AlterField(
            model_name='glutenfreefood',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_%(class)s_items', to=settings.AUTH_USER_MODEL, verbose_name='Ekleyen'),
        ),
        migrations.AlterField(
            model_name='glutenfreefood',
            name='approved_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Onay Tarihi'),
        ),
        migrations.AlterField(
            model_name='glutenfreefood',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.foodbrand', verbose_name='Marka'),
        ),
        migrations.RemoveField(
            model_name='glutenfreefood',
            name='category',
        ),
        migrations.AlterField(
            model_name='glutenfreefood',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='glutenfreefood',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Onaylı mı?'),
        ),
        migrations.AlterField(
            model_name='glutenfreefood',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Ürün Adı'),
        ),
        migrations.AlterField(
            model_name='glutenfreehotel',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_%(class)s_items', to=settings.AUTH_USER_MODEL, verbose_name='Ekleyen'),
        ),
        migrations.AlterField(
            model_name='glutenfreehotel',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='glutenfreehotel',
            name='approved_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Onay Tarihi'),
        ),
        migrations.AlterField(
            model_name='glutenfreehotel',
            name='contact',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='İletişim'),
        ),
        migrations.AlterField(
            model_name='glutenfreehotel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='glutenfreehotel',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Onaylı mı?'),
        ),
        migrations.AlterField(
            model_name='glutenfreehotel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Otel Adı'),
        ),
        migrations.AlterField(
            model_name='glutenfreehotel',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Web Sitesi'),
        ),
        migrations.AlterField(
            model_name='glutenfreemedicine',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_%(class)s_items', to=settings.AUTH_USER_MODEL, verbose_name='Ekleyen'),
        ),
        migrations.AlterField(
            model_name='glutenfreemedicine',
            name='approved_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Onay Tarihi'),
        ),
        migrations.AlterField(
            model_name='glutenfreemedicine',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.medicinebrand', verbose_name='Marka'),
        ),
        migrations.AlterField(
            model_name='glutenfreemedicine',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Onaylı mı?'),
        ),
        migrations.AlterField(
            model_name='glutenfreemedicine',
            name='name',
            field=models.CharField(max_length=100, verbose_name='İlaç Adı'),
        ),
        migrations.AlterField(
            model_name='glutenfreerecipe',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_%(class)s_items', to=settings.AUTH_USER_MODEL, verbose_name='Ekleyen'),
        ),
        migrations.AlterField(
            model_name='glutenfreerecipe',
            name='approved_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Onay Tarihi'),
        ),
        migrations.AlterField(
            model_name='glutenfreerecipe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='glutenfreerecipe',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='glutenfreerecipe',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Onaylı mı?'),
        ),
        migrations.AlterField(
            model_name='glutenfreerecipe',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tarif Adı'),
        ),
        migrations.AlterField(
            model_name='glutenfreevenue',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_%(class)s_items', to=settings.AUTH_USER_MODEL, verbose_name='Ekleyen'),
        ),
        migrations.AlterField(
            model_name='glutenfreevenue',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='glutenfreevenue',
            name='approved_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Onay Tarihi'),
        ),
        migrations.AlterField(
            model_name='glutenfreevenue',
            name='contact',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='İletişim'),
        ),
        migrations.AlterField(
            model_name='glutenfreevenue',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='glutenfreevenue',
            name='gluten_free_products',
            field=models.TextField(blank=True, null=True, verbose_name='Glutensiz Ürünler'),
        ),
        migrations.AlterField(
            model_name='glutenfreevenue',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Onaylı mı?'),
        ),
        migrations.AlterField(
            model_name='glutenfreevenue',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Mekan Adı'),
        ),
        migrations.AlterField(
            model_name='medicinebrand',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='İlaç Markası'),
        ),
        migrations.AddField(
            model_name='glutenfreefood',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.category', verbose_name='Kategori'),
        ),
    ]
