# Generated by Django 4.2.7 on 2025-07-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_brand_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_edit_foods',
            field=models.BooleanField(default=False, verbose_name='Glutensiz Gıda Yetki'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_edit_hotels',
            field=models.BooleanField(default=False, verbose_name='Glutensiz Otel Yetki'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_edit_medicines',
            field=models.BooleanField(default=False, verbose_name='Glutensiz İlaç Yetki'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_edit_recipes',
            field=models.BooleanField(default=False, verbose_name='Glutensiz Tarif Yetki'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_edit_venues',
            field=models.BooleanField(default=False, verbose_name='Glutensiz Mekan Yetki'),
        ),
    ]
