# Generated by Django 5.2.4 on 2025-07-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_can_edit_foods_user_can_edit_hotels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='glutenfreemedicine',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='glutenfreerecipe',
            name='ingredients',
            field=models.TextField(blank=True, null=True, verbose_name='Malzemeler'),
        ),
    ]
