# Generated by Django 4.2.7 on 2025-07-15 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_glutenfreemedicine_description_and_more'),
    ]

    operations = [
    ]
