# Generated by Django 5.2.4 on 2025-07-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20250715_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='glutenfreerecipe',
            name='instructions',
            field=models.TextField(blank=True, null=True, verbose_name='Hazırlanış'),
        ),
    ]
