# Generated by Django 4.2.7 on 2025-07-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_glutenfreerecipe_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='glutenfreerecipe',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Öne Çıkarılmış mı?'),
        ),
    ]
