# Generated by Django 4.2.7 on 2025-07-15 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_glutenfreerecipe_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='glutenfreerecipe',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.category', verbose_name='Kategori'),
        ),
    ]
