# Generated by Django 5.2.4 on 2025-07-10 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GlutenFreeFood',
        ),
        migrations.DeleteModel(
            name='GlutenFreeHotel',
        ),
        migrations.DeleteModel(
            name='GlutenFreeMedicine',
        ),
        migrations.DeleteModel(
            name='GlutenFreeRecipe',
        ),
        migrations.DeleteModel(
            name='GlutenFreeVenue',
        ),
    ]
